/*
  # Populate Suppliers Data

  1. Data Import
    - Insert all suppliers from the provided data file
    - Includes suppliers from Amsterdam, Barcelona, Berlin, Bremen, and Bruges
    - Covers attractions, accommodations, and restaurants
  
  2. Data Structure
    - All suppliers with complete contact information
    - Category, focus, pricing, and notes included
    - Formatted for educational tour planning
*/

-- Insert Amsterdam suppliers
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Rijksmuseum', 'Attractions', 'Art and History', 'Museumstraat 1, 1071 XX Amsterdam', 'Amsterdam', '+31 20 674 7000', 'info@rijksmuseum.nl', 'riksmuseum.nl', 'Free for under 18s', 'Iconic Dutch art and history; offers guided tours for school groups; interactive workshops and educational programs available.'),
('Anne Frank House', 'Attractions', 'Historical Museum', 'Westerkerk 20, 1016 GV Amsterdam', 'Amsterdam', '+31 20 556 7100', 'info@annefrank.org', 'annefrank.org', '€7 per student', 'Focuses on Anne Frank''s life and the Holocaust; online reservations required; suitable for history lessons about WWII and tolerance.'),
('NEMO Science Museum', 'Attractions', 'Science and Technology', 'Oosterdok 2, 1011 VX Amsterdam', 'Amsterdam', '+31 20 531 3233', 'info@nemosciencemuseum.nl', 'nemosciencemuseum.nl', 'Free for school groups', 'Hands-on science exhibits; workshops and group tours available; designed to engage children in STEM subjects.'),
('Van Gogh Museum', 'Attractions', 'Art and Culture', 'Museumplein 6, 1071 DJ Amsterdam', 'Amsterdam', '+31 20 570 5200', 'info@vangoghmuseum.nl', 'vangoghmuseum.nl', 'Free for under 18s', 'Dedicated to the works of Vincent van Gogh; offers group discounts and educational materials for art students.'),
('Artis Royal Zoo', 'Attractions', 'Wildlife and Conservation', 'Plantage Kerklaan 38-40, 1018 CZ Amsterdam', 'Amsterdam', '+31 20 523 3400', 'info@artis.nl', 'artis.nl', 'Varies', 'Zoo with a focus on education; includes a planetarium, aquarium, and butterfly pavilion; group discounts and guided tours available.'),
('Canal Cruise', 'Attractions', 'Cultural Exploration', 'Various departure points', 'Amsterdam', '+31 20 000 0000', 'info@stromma.com', 'stromma.com', '€11.25 per child', 'Educational cruises available with commentary about Amsterdam''s history; private group bookings can be arranged; provides a unique perspective of the city.'),
('Micropia', 'Attractions', 'Microbiology Museum', 'Plantage Kerklaan 38-40, 1018 CZ Amsterdam', 'Amsterdam', '+31 20 523 3670', 'info@micropia.nl', 'micropia.nl', '€8 per student', 'Focuses on microorganisms; interactive exhibits; great for biology and science-focused school groups; located near Artis Royal Zoo.'),
('Amsterdam Dungeon', 'Attractions', 'History and Entertainment', 'Rokin 78, 1012 KW Amsterdam', 'Amsterdam', '+31 20 530 8500', 'info@the-dungeons.nl', 'the-dungeons.nl', '€19.75 per student', 'Engaging and theatrical storytelling of Amsterdam''s dark history; group discounts available; suitable for older children.'),
('EYE Film Museum', 'Attractions', 'Film and Media', 'IJpromenade 1, 1031 KT Amsterdam', 'Amsterdam', '+31 20 589 1400', 'info@eyefilm.nl', 'eyefilm.nl', 'Free for school groups', 'Focuses on cinema and media; offers workshops for school groups; located in a modern building with stunning views of the IJ river.'),
('Tropenmuseum', 'Attractions', 'Anthropology and Culture', 'Linnaeusstraat 2, 1092 CK Amsterdam', 'Amsterdam', '+31 20 568 8200', 'info@tropenmuseum.nl', 'tropenmuseum.nl', 'Free for under 18s', 'World cultures museum; educational programs and guided tours on various topics available.');

-- Insert Amsterdam accommodations
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Stayokay Amsterdam Oost', 'Accommodation', 'Hostel, budget-friendly', 'Timorplein 21, 1094 CC Amsterdam', 'Amsterdam', '+31 20 551 3190', 'amsterdam@stayokay.com', 'stayokay.com', '€25–€40 per person/night', 'Large rooms suitable for groups; offers breakfast and lunch options; close to public transport; activities like bike rentals available.'),
('ClinkNOORD Hostel', 'Accommodation', 'Modern hostel', 'Badhuiskade 3, 1031 KV Amsterdam', 'Amsterdam', '+31 20 214 0790', 'info@clinkhostels.com', 'clinkhostels.com', '€25–€40 per person/night', 'Conveniently located in Amsterdam Noord; group discounts available; on-site restaurant and café; easy access to city center via free ferry.'),
('Meininger Hotel Amsterdam City West', 'Accommodation', 'Hotel with hostel-like vibe', 'Orlyplein 1-67, 1043 DR Amsterdam', 'Amsterdam', '+31 20 308 0190', 'info@meininger-hotels.com', 'meininger-hotels.com', '€30–€50 per person/night', 'Family and group-friendly accommodation; offers shared or private rooms; well-connected via train and metro; 24/7 reception and lounge.'),
('A&O Amsterdam Zuidoost', 'Accommodation', 'Budget hotel/hostel', 'Hogehilweg 22, 1101 CD Amsterdam', 'Amsterdam', '+31 20 258 9100', 'info@aohostels.com', 'aohostels.com', '€20–€35 per person/night', 'Group rooms with bunk beds; affordable meals available; located near Amsterdam Arena; public transport options nearby for easy access to attractions.'),
('The Student Hotel Amsterdam City', 'Accommodation', 'Hotel with modern amenities', 'Wibautstraat 129, 1091 GL Amsterdam', 'Amsterdam', '+31 20 214 9999', 'info@thestudenthotel.com', 'thestudenthotel.com', '€40–€70 per person/night', 'Trendy, modern spaces; study areas and recreation zones; offers group rates; near public transport and cultural attractions.'),
('Hotel Casa Amsterdam', 'Accommodation', 'Affordable hotel', 'Eerste Ringdijkstraat 4, 1097 BC Amsterdam', 'Amsterdam', '+31 20 665 1171', 'info@hotelcasa.nl', 'hotelcasa.nl', '€35–€60 per person/night', 'Clean and spacious rooms; rooftop terrace available; group dining options; located near metro station for convenient access to city center.'),
('Hans Brinker Hostel', 'Accommodation', 'Budget-friendly hostel', 'Kerkstraat 136, 1017 GR Amsterdam', 'Amsterdam', '+31 20 622 0687', 'info@hansbrinker.com', 'hansbrinker.com', '€20–€30 per person/night', 'Known for its affordable prices; offers group accommodations; breakfast included; walking distance to many city attractions.'),
('WOW Amsterdam', 'Accommodation', 'Art-themed hostel', 'Wiltzanghlaan 60, 1061 HC Amsterdam', 'Amsterdam', '+31 20 890 0005', 'info@wow-amsterdam.nl', 'wow-amsterdam.nl', '€25–€45 per person/night', 'Features an art studio and communal garden; offers group accommodation and is suitable for creative school trips.');

-- Insert Amsterdam restaurants
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Pannenkoekenhuis Candela', 'Restaurants', 'Dutch pancakes', 'Bilderdijkstraat 61, 1053 KL Amsterdam', 'Amsterdam', '+31 20 618 9090', 'info@candela.nl', 'candela.nl', '€8–€12', 'Offers a variety of sweet and savory pancakes; casual setting; suitable for children; group-friendly atmosphere.'),
('Skek', 'Restaurants', 'Dutch fusion, student-run', 'Zeedijk 4-8, 1012 AX Amsterdam', 'Amsterdam', '+31 20 427 3888', 'info@skek.nl', 'skek.nl', '€13–€18', 'Student-run restaurant offering traditional Dutch food with modern twists; live music nights; vibrant atmosphere; caters well to groups.'),
('Kauffmann Falafel', 'Restaurants', 'Middle Eastern fast food', 'Reinier Claeszenstraat 4, 1056 WN Amsterdam', 'Amsterdam', '+31 20 737 1247', 'info@kauffmannfalafel.nl', 'kauffmannfalafel.nl', '€6–€10', 'Specializes in falafel pitas with various toppings; casual and quick service; suitable for groups seeking a fast, affordable meal.'),
('La Perla', 'Restaurants', 'Italian (wood-fired pizza)', 'Tweede Tuindwarsstraat 14, 1015 RZ Amsterdam', 'Amsterdam', '+31 20 624 8828', 'info@laperla.nl', 'laperla.nl', '€12–€16', 'Authentic Italian pizzas made with imported ingredients; cozy atmosphere; suitable for small to medium-sized groups.'),
('Dwaze Zaken', 'Restaurants', 'Fusion cuisine', 'Prins Hendrikkade 50, 1012 AC Amsterdam', 'Amsterdam', '+31 20 421 1919', 'info@dwazezaken.nl', 'dwazezaken.nl', '€15–€20', 'Offers a diverse menu with vegetarian options; artistic decor; relaxed environment; accommodates groups.'),
('Cuisine of India', 'Restaurants', 'Indian cuisine', 'Binnen Bantammerstraat 9A, 1011 CH Amsterdam', 'Amsterdam', '+31 20 330 0000', 'info@cuisineofindia.nl', 'thefork.com', '€29', 'Traditional Indian dishes; group discounts available; suitable for larger groups.'),
('Rangla Punjab', 'Restaurants', 'Indian cuisine', 'Overtoom 350, 1054 JG Amsterdam', 'Amsterdam', '+31 20 612 1234', 'info@ranglapunjab.nl', 'thefork.com', '€29', 'Authentic Punjabi dishes; offers group menus; comfortable for school groups.'),
('The Vegan Indian', 'Restaurants', 'Vegan Indian cuisine', 'Lange Leidsedwarsstraat 108, 1017 NN Amsterdam', 'Amsterdam', '+31 20 223 4567', 'info@thevegaindian.nl', 'thefork.com', '€29', 'Plant-based Indian dishes; caters to dietary restrictions; group-friendly.');

-- Insert Barcelona suppliers
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Sagrada Família', 'Attractions', 'Iconic basilica designed by Antoni Gaudí; focus on architecture and art', 'Carrer de Mallorca, 401, 08013 Barcelona', 'Barcelona', '+34 932 08 04 14', 'info@sagradafamilia.org', 'www.sagradafamilia.org', '€17–€20 per student', 'Offers educational tours for groups; tickets must be booked in advance for school visits.'),
('Park Güell', 'Attractions', 'Public park featuring Gaudí''s colorful mosaics and unique architecture', 'Carrer d''Olot, s/n, 08024 Barcelona', 'Barcelona', '+34 934 09 18 31', 'info@parkguell.barcelona', 'www.parkguell.barcelona', '€7 per student', 'Group tours available with interactive learning about art and nature; pre-booking required.'),
('Camp Nou Experience', 'Attractions', 'Football stadium tour, including the FC Barcelona Museum', 'C. d''Arístides Maillol, 12, 08028 Barcelona', 'Barcelona', '+34 902 18 99 00', 'info@fcbarcelona.com', 'www.fcbarcelona.com', '€22 per student', 'Great for sports enthusiasts; interactive exhibits and tours tailored for school groups.'),
('CosmoCaixa Science Museum', 'Attractions', 'Hands-on science museum with exhibits on natural history, technology, and space', 'Carrer d''Isaac Newton, 26, 08022 Barcelona', 'Barcelona', '+34 932 12 60 50', 'info@cosmocaixa.org', 'www.cosmocaixa.org', 'Free admission', 'Offers group discounts and guided tours; highly interactive and engaging for children.'),
('Barcelona Aquarium', 'Attractions', 'Focus on marine life with a large oceanarium and interactive exhibits', 'Moll d''Espanya del Port Vell, s/n, 08039 Barcelona', 'Barcelona', '+34 932 21 74 74', 'info@aquariumbcn.com', 'www.aquariumbcn.com', '€14–€22 per child', 'Offers educational programs and group visits.'),
('Gothic Quarter', 'Attractions', 'Historic district with narrow medieval streets and cultural landmarks', 'La Rambla, 08002 Barcelona', 'Barcelona', '+34 932 85 38 34', 'info@barcelonaturisme.com', 'barcelonaturisme.com', 'Free', 'Great for a guided stroll; nearby markets like La Boqueria offer cultural and culinary experiences.'),
('Montserrat Monastery', 'Attractions', 'Historic monastery with stunning mountain views', '08199 Monistrol de Montserrat, Barcelona', 'Barcelona', '+34 938 77 77 77', 'info@montserratvisita.com', 'www.montserratvisita.com', 'Varies', 'Ideal for day trips; offers guided tours and educational content about history and religion.'),
('Chocolate Museum (Museu de la Xocolata)', 'Attractions', 'Focus on the history and production of chocolate; fun and interactive', 'Carrer del Comerç, 36, 08003 Barcelona', 'Barcelona', '+34 932 68 78 78', 'info@museuxocolata.cat', 'www.museuxocolata.cat', '€9.50–€22 per student', 'Perfect for younger children; includes workshops and group activities about chocolate-making.'),
('Tibidabo Amusement Park', 'Attractions', 'Historic amusement park with rides, views of Barcelona, and educational programs', 'Plaça del Tibidabo, 3-4, 08035 Barcelona', 'Barcelona', '+34 934 11 94 42', 'info@tibidabo.cat', 'www.tibidabo.cat', 'Varies', 'Offers group packages; combines entertainment with stunning views of the city.'),
('Ciutadella Park and Zoo', 'Attractions', 'Large park with open spaces for group activities and a zoo with diverse animal species', 'Parc de la Ciutadella, 08003 Barcelona', 'Barcelona', '+34 932 25 67 80', 'info@zoobarcelona.cat', 'www.zoobarcelona.cat', '€12 per child (online)', 'Perfect for outdoor activities; the zoo offers educational programs for schools.');

-- Insert Barcelona accommodations
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Generator Barcelona', 'Accommodation', 'Trendy, budget-friendly hostel with group rooms', 'Carrer de Còrsega, 373-377, 08037 Barcelona', 'Barcelona', '+34 932 20 37 37', 'barcelona@generatorhostels.com', 'www.generatorhostels.com', '€20–€40 per person/night', 'Offers group discounts, centrally located near Sagrada Família and Passeig de Gràcia.'),
('Equity Point Centric Hostel', 'Accommodation', 'Youth hostel with a focus on group travelers', 'Passeig de Gràcia, 33, 08007 Barcelona', 'Barcelona', '+34 932 31 31 91', 'info@equity-point.com', 'www.equity-point.com', '€18–€35 per person/night', 'Spacious dormitories and private rooms; located in a historic building near major landmarks.'),
('Hostal Mare Nostrum', 'Accommodation', 'Family-friendly hostel with affordable rates', 'Carrer de Sant Pau, 2, 08001 Barcelona', 'Barcelona', '+34 933 19 32 62', 'info@hostalmarenostrum.com', 'www.hostalmarenostrum.com', '€25–€50 per person/night', 'Located near La Rambla; ideal for groups exploring central Barcelona.'),
('Alberg Pere Tarrés Youth Hostel', 'Accommodation', 'Budget hostel offering group accommodations and meal plans', 'Carrer de Numància, 149-151, 08029 Barcelona', 'Barcelona', '+34 934 10 23 30', 'info@peretarres.org', 'www.peretarres.org', 'From €19 per person/night', 'Includes group discounts, large dining areas, and easy access to public transport.'),
('St. Christopher''s Inn', 'Accommodation', 'Modern hostel with dormitories and group-friendly amenities', 'Carrer de Bergara, 3, 08002 Barcelona', 'Barcelona', '+34 931 77 36 75', 'barcelona@st-christophers.co.uk', 'www.st-christophers.co.uk', '€20–€45 per person/night', 'Located near Plaça de Catalunya; offers group meals and discounts.'),
('Urbany Hostel Barcelona', 'Accommodation', 'Vibrant, youth-focused hostel with group packages', 'Avinguda Meridiana, 97, 08026 Barcelona', 'Barcelona', '+34 932 45 25 21', 'info@urbanyhostels.com', 'www.urbanyhostels.com', '€15–€30 per person/night', 'Includes meeting rooms, private group areas, and modern facilities near Sagrada Família.'),
('Hotel Jazz', 'Accommodation', 'Mid-range hotel offering family rooms and group accommodations', 'Carrer de Pelai, 3, 08001 Barcelona', 'Barcelona', '+34 935 48 99 66', 'info@hoteljazz.com', 'www.hoteljazz.com', '€60–€100 per person/night', 'Central location near La Rambla and Plaça de Catalunya; suitable for older school groups.'),
('Casa Gracia', 'Accommodation', 'Boutique hostel with large group rooms and communal spaces', 'Passeig de Gràcia, 116 bis, 08008 Barcelona', 'Barcelona', '+34 931 87 44 97', 'info@casagraciabcn.com', 'www.casagraciabcn.com', '€25–€55 per person/night', 'Stylish and centrally located; great for combining education and comfort for school groups.'),
('Sant Jordi Hostel Gracia', 'Accommodation', 'Eco-friendly hostel with group-friendly dormitories and common areas', 'Carrer de Terol, 35, 08012 Barcelona', 'Barcelona', '+34 932 18 19 29', 'info@santjordihostels.com', 'www.santjordihostels.com', '€18–€35 per person/night', 'Located in a lively area; offers group activities and is committed to sustainable tourism.');

-- Insert Barcelona restaurants
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Tapa Tapa', 'Restaurants', 'Casual dining offering a variety of traditional Spanish tapas', 'Passeig de Gràcia, 44, 08007 Barcelona', 'Barcelona', '+34 933 18 96 21', 'info@tapatapa.com', 'www.tapatapa.com', '€15–€20', 'Large dining area, perfect for introducing students to Spanish cuisine.'),
('La Fonda', 'Restaurants', 'Affordable Mediterranean and Spanish cuisine', 'Carrer dels Escudellers, 10, 08002 Barcelona', 'Barcelona', '+34 933 01 75 15', 'info@lafondabcn.com', 'lafondabcn.com', '€15–€20', 'Offers group-friendly menus with paella and classic Spanish dishes.'),
('El Nacional Barcelona', 'Restaurants', 'Food hall with multiple restaurants featuring Spanish and Mediterranean specialties', 'Passeig de Gràcia, 24 Bis, 08007 Barcelona', 'Barcelona', '+34 935 18 50 53', 'info@elnacionalbcn.com', 'www.elnacionalbcn.com', '€20–€25', 'Stylish venue offering diverse food options; good for larger groups.'),
('Cervecería 100 Montaditos', 'Restaurants', 'Casual chain serving small sandwiches and tapas', 'Various locations in Barcelona', 'Barcelona', '+34 900 100 100', 'info@100montaditos.com', 'www.100montaditos.com', '€10–€15', 'Affordable and casual; ideal for quick meals for large groups.'),
('Restaurant Salamanca', 'Restaurants', 'Seafood and traditional Spanish dishes, including paella', 'Carrer de l''Almirall Cervera, 34, 08003 Barcelona', 'Barcelona', '+34 932 21 50 33', 'info@restaurantesalamanca.com', 'www.restaurantesalamanca.com', '€20–€30', 'Offers group menus; located near Barceloneta Beach.'),
('La Tagliatella', 'Restaurants', 'Italian restaurant chain serving pizzas and pastas', 'Various locations in Barcelona', 'Barcelona', '+34 934 16 40 64', 'info@latagliatella.es', 'www.latagliatella.es', '€15–€20', 'Family-friendly; great for students preferring Italian cuisine.'),
('Pans & Company', 'Restaurants', 'Fast-casual chain offering sandwiches and salads', 'Multiple locations across Barcelona', 'Barcelona', '+34 900 50 20 45', 'info@pansandcompany.com', 'www.pansandcompany.com', '€8–€12', 'Quick and budget-friendly option for groups on the go.'),
('La Boqueria Market (Food Stalls)', 'Restaurants', 'Fresh local food and diverse dining options from market stalls', 'La Rambla, 91, 08001 Barcelona', 'Barcelona', '+34 933 18 25 84', 'info@boqueria.barcelona', 'www.boqueria.barcelona', '€10–€15', 'A lively experience; groups can explore local foods while dining affordably.'),
('Sagardi BCN Gòtic', 'Restaurants', 'Basque cuisine with pintxos and grilled dishes', 'Carrer de l''Argenteria, 62, 08003 Barcelona', 'Barcelona', '+34 933 10 24 53', 'info@sagardi.es', 'www.sagardi.es/restaurantes/sagardi-bcn-gotic', '€20–€30', 'Offers group menus and a unique culinary experience.');

-- Insert Berlin suppliers
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('DDR Museum', 'Attractions', 'Interactive exploration of life in East Germany', 'Karl-Liebknecht-Str. 1, 10178 Berlin', 'Berlin', '+49 30 847 123 7-32', 'info@ddr-museum.de', 'www.ddr-museum.de/en/visit/school-classes-and-groups/group-booking', '€5 per student', 'Offers guided tours and workshops; school group rate is €5 per student (minimum 10 students).'),
('Jewish Museum Berlin', 'Attractions', 'Jewish history and culture in Germany', 'Lindenstraße 9–14, 10969 Berlin', 'Berlin', '+49 30 259 93 305', 'info@jmberlin.de', 'www.jmberlin.de/en/programs-for-school-groups', '€4 per student', 'Offers various educational programs; advance booking recommended.'),
('Berlin Cathedral (Berliner Dom)', 'Attractions', 'Historic Protestant cathedral with breathtaking architecture', 'Am Lustgarten, 10178 Berlin', 'Berlin', '+49 30 20269136', 'info@berlinerdom.de', 'www.berlinerdom.de/en/visit/groups/', '€4 per student', 'Offers guided tours for groups and school classes, focusing on history and architecture.'),
('Berlin Wall Memorial', 'Attractions', 'Historical site with preserved sections of the Berlin Wall and exhibits about its history', 'Bernauer Str. 111, 13355 Berlin', 'Berlin', '+49 30 467986666', 'info@berliner-mauer-gedenkstaette.de', 'www.berliner-mauer-gedenkstaette.de/en/', 'Free', 'Guided tours and workshops available for school groups; pre-booking required.'),
('East Side Gallery', 'Attractions', 'Open-air gallery featuring murals on a preserved section of the Berlin Wall', 'Mühlenstraße 3-100, 10243 Berlin', 'Berlin', '+49 30 251 7159', 'info@eastsidegallery-berlin.de', 'eastsidegallery-berlin.de', 'Free', 'Free and open to the public; an excellent historical and artistic experience for groups.'),
('German Historical Museum (Deutsches Historisches Museum)', 'Attractions', 'German history, from ancient times to the present day', 'Unter den Linden 2, 10117 Berlin', 'Berlin', '+49 30 20304-444', 'info@dhm.de', 'www.dhm.de/en/education/', 'Free for under 18s', 'Offers educational programs and guided tours on various historical periods.'),
('German Spy Museum Berlin', 'Attractions', 'History of espionage and intelligence', 'Leipziger Platz 9, 10117 Berlin', 'Berlin', '+49 30 398200451', 'info@deutsches-spionagemuseum.de', 'www.deutsches-spionagemuseum.de/en/visit/school-groups', '€10 per student', 'Group tours available; maximum of 25 persons per tour.'),
('The Holocaust Memorial', 'Attractions', 'Memorial and educational site about the Holocaust', 'Cora-Berliner-Straße 1, 10117 Berlin', 'Berlin', '+49 30 26 39 43 36', 'info@stiftung-denkmal.de', 'www.stiftung-denkmal.de/en/memorials/memorial-to-the-murdered-jews-of-europe', 'Free', 'Guided tours and workshops are available; bookings required for groups.'),
('The Reichstag Building', 'Attractions', 'German parliament and historical landmark', 'Platz der Republik 1, 11011 Berlin', 'Berlin', '+49 30 22732152', 'info@bundestag.de', 'www.bundestag.de/en/visittheBundestag/dome/registration-245686', 'Free', 'Free tours available, including visits to the glass dome; advance booking is essential for group visits.'),
('Memorial & Museum Sachsenhausen', 'Attractions', 'Nazi concentration camp history and education', 'Straße der Nationen 22, 16515 Oranienburg', 'Berlin', '+49 3301 200200', 'info@sachsenhausen-sbg.de', 'www.sachsenhausen-sbg.de/en/education/visiting', 'Free', 'Offers educational programs, including guided tours and workshops tailored for school groups. Advanced booking required.');

-- Insert Berlin accommodations
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('MEININGER Hotel Berlin Tiergarten', 'Accommodation', 'Ideal for groups with multi-bed rooms, game zones, and packed lunch options', 'Turmstr. 25 (Stromstr.), 10559 Berlin', 'Berlin', '+49 30 666363510', 'berlin@meininger-hotels.com', 'www.meininger-hotels.com', '€24–€48 per person/night', 'Centrally located, near Bellevue Palace and Government District.'),
('Amadeus Hostel Berlin', 'Accommodation', 'Group accommodations with 2–4 bed dormitories and private rooms for teachers', 'Brunnenstr. 70, 13355 Berlin', 'Berlin', '+49 30 46720700', 'info@amadeus-hostel-berlin.com', 'amadeus-hostel-berlin.com', '€20–€30 per person/night', 'Assistance with daily program planning.'),
('aletto Hotel Kudamm', 'Accommodation', 'Caters to school trips with accommodations near major attractions', 'Hardenbergstr. 21, 10623 Berlin', 'Berlin', '+49 30 80941580', 'info@aletto.com', 'www.aletto.com', '€25–€35 per person/night', 'Offers hotel planning support.'),
('Citylight Hotel', 'Accommodation', 'Family-friendly hotel with excellent transport links and park access', 'Böttgerstr. 23, 13357 Berlin', 'Berlin', '+49 30 4950000', 'info@citylight-hotel.de', 'www.citylight-hotel.de', '€29 per person/night', 'Close to Gesundbrunnen station and Humboldthain Park.'),
('Pegasus Hostel', 'Accommodation', 'Hostel in Friedrichshain-Kreuzberg, near Alexanderplatz', 'Straße der Pariser Kommune 35, 10243 Berlin', 'Berlin', '+49 30 29773550', 'info@pegasushostel.de', 'www.pegasushostel.de', '€20–€30 per person/night', 'Provides assistance with tours and organizing school trips.'),
('Industriepalast Hostel Berlin', 'Accommodation', 'Affordable group accommodations in the Friedrichshain district', 'Warschauer Str. 43-44, 10243 Berlin', 'Berlin', '+49 30 29667005', 'info@ip-hostel.com', 'www.ip-hostel.com', '€12–€28 per person/night', 'Offers group activities and 24/7 staff support.'),
('The Circus Hostel', 'Accommodation', 'Hostel with a friendly atmosphere and group accommodation options', 'Weinbergsweg 1a, 10119 Berlin', 'Berlin', '+49 30 20003939', 'info@circus-berlin.de', 'www.circus-berlin.de', '€14–€30 per person/night', 'Located in central Mitte, perfect for group exploration of Berlin.'),
('A&O Berlin Hauptbahnhof', 'Accommodation', 'Hostel with affordable group rates and family-friendly amenities', 'Lehrter Str. 12-15, 10557 Berlin', 'Berlin', '+49 30 80947510', 'info@aohostels.com', 'www.aohostels.com', '€18–€35 per person/night', 'Close to Berlin''s main train station and government district.');

-- Insert Berlin restaurants
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Café am Neuen See', 'Restaurants', 'Located in Tiergarten, offers a great atmosphere and large outdoor seating area', 'Lichtensteinallee 2, 10787 Berlin', 'Berlin', '+49 30 30110090', 'info@cafeamneuensee.de', 'www.cafeamneuensee.de', '€10–€20', 'Perfect for groups, with a large outdoor area by the lake, ideal for school outings.'),
('Mustafa''s Gemüse Kebap', 'Restaurants', 'Famous for its Turkish döner kebabs and quick service', 'Mehringdamm 32, 10961 Berlin', 'Berlin', '+49 30 61420374', 'info@mustafas.de', 'www.mustafas.de', '€5–€10', 'Great for fast and affordable meals, popular with both locals and tourists.'),
('Biergarten Prater', 'Restaurants', 'Traditional German beer garden with hearty dishes and group seating', 'Kastanienallee 7-9, 10435 Berlin', 'Berlin', '+49 30 4473516', 'info@pratergarten-berlin.de', 'www.pratergarten-berlin.de', '€10–€20', 'A large, casual beer garden perfect for large groups, serving traditional German food.'),
('Zur letzten Instanz', 'Restaurants', 'Historic restaurant serving traditional German cuisine, ideal for group events', 'Waisenstr. 14-16, 10179 Berlin', 'Berlin', '+49 30 25354270', 'info@zurletzteninstanz.de', 'www.zurletzteninstanz.de', '€15–€25', 'One of Berlin''s oldest restaurants, offers group menus and a historical atmosphere.'),
('Konnopke''s Imbiss', 'Restaurants', 'Serving classic Berlin street food (Currywurst and sausages)', 'Schönhauser Allee 44b, 10435 Berlin', 'Berlin', '+49 30 4413068', 'info@konnopkes.de', 'www.konnopkes.de', '€5–€10', 'Known for its currywurst, great for quick and affordable meals in a casual setting.'),
('Fleischerei', 'Restaurants', 'A cozy butcher shop-turned-restaurant offering affordable meat-based dishes', 'Friedrichstr. 103, 10117 Berlin', 'Berlin', '+49 30 32291515', 'info@fleischerei.berlin', 'www.fleischerei.berlin', '€10–€20', 'Offers high-quality meats in a relaxed, group-friendly setting.'),
('Burgers & Hip Hop', 'Restaurants', 'American-style burgers and comfort food, ideal for groups of all sizes', 'Eberswalder Str. 24, 10437 Berlin', 'Berlin', '+49 30 57709355', 'info@burgersandhiphop.de', 'www.burgersandhiphop.de', '€8–€15', 'Offers fun and informal dining, with options for larger groups and student-friendly meals.'),
('Café Einstein Stammhaus', 'Restaurants', 'Elegant Viennese café offering affordable group-friendly options, with classic dishes', 'Kurfürstenstraße 58, 10785 Berlin', 'Berlin', '+49 30 26187861', 'info@cafeeinstein.com', 'www.cafeeinstein.com', '€10–€20', 'Classic European café, great for school groups looking for a mix of elegance and affordability.'),
('Neni Berlin', 'Restaurants', 'Mediterranean-inspired cuisine in a trendy setting, with options for group dining', 'Budapester Str. 40, 10787 Berlin', 'Berlin', '+49 30 120855215', 'info@neni.at', 'neni.at/restaurants/berlin', '€20–€30', 'Offers a variety of dishes for sharing, ideal for group settings.');

-- Insert Bremen suppliers
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Universum Bremen', 'Attractions', 'Science Museum & Interactive Exhibits', 'Wiener Str. 1a, 28359 Bremen', 'Bremen', '+49 421 220 70 00', 'info@universum-bremen.de', 'www.universum-bremen.de', '€12 per student', 'Hands-on science exhibits, ideal for children; educational workshops available.'),
('Bremen Town Musicians Statue', 'Attractions', 'Fairy tale & local landmark', 'Am Marktplatz, 28195 Bremen', 'Bremen', '+49 421 361 6161', 'info@bremen-tourism.de', 'www.bremen-tourism.de', 'Free', 'Iconic statue from Brothers Grimm tale; great for storytelling and photos.'),
('Übersee-Museum Bremen', 'Attractions', 'World cultures & natural history', 'Bahnhofsplatz 13, 28195 Bremen', 'Bremen', '+49 421 160 50 00', 'info@uebersee-museum.de', 'www.uebersee-museum.de', 'Free for under 18s', 'Exhibits on cultures, animals, and plants; interactive elements for kids.'),
('Rhododendron-Park Bremen', 'Attractions', 'Botanical garden & park', 'Am Rhododendronpark 4, 28359 Bremen', 'Bremen', '+49 421 361 82 20', 'info@rhododendronpark-bremen.de', 'www.rhododendronpark-bremen.de', 'Free', 'Large park with diverse plants, walking trails, and playgrounds; good for outdoor learning.'),
('Focke Museum', 'Attractions', 'History and art museum', 'Schwachhauser Heerstr. 240, 28213 Bremen', 'Bremen', '+49 421 590 39 0', 'info@focke-museum.de', 'www.focke-museum.de', 'Free for under 18s', 'Focus on Bremen''s history; school group tours and workshops available.'),
('Weser Stadium (Weserstadion)', 'Attractions', 'Sports and cultural landmark', 'Franz-Böhmert-Straße 1c, 28205 Bremen', 'Bremen', '+49 421 434 50 0', 'info@werder.de', 'www.werder.de', 'Varies', 'Home of SV Werder Bremen; guided tours of the stadium available for sports fans.');

-- Insert Bremen accommodations
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('DJH Jugendherberge Bremen', 'Accommodation', 'Youth hostel, eco-certified', 'Kalkstraße 6, 28195 Bremen', 'Bremen', '+49 421 3301 290', 'bremen@jugendherberge.de', 'bremen.jugendherberge.de', '€20–€30 per person/night', '254 beds, group discounts, wheelchair accessible, family-friendly, catering options available'),
('ibis budget Bremen City Center', 'Accommodation', 'Budget hotel, basic amenities', 'Bahnhofsplatz 41, 28195 Bremen', 'Bremen', '+49 421 3355 2000', 'info@ibisbudget-bremen.com', 'all.accor.com/hotel/A052/index.de', '€35–€60 per person/night', 'Affordable, family rooms, close to city center and attractions'),
('Radisson Blu Bremen', 'Accommodation', 'Premium hotel, spacious rooms', 'Böttcherstr. 2, 28195 Bremen', 'Bremen', '+49 421 33960', 'info@radissonblu-bremen.com', 'radissonhotels.com/en-us/hotels/radisson-blu-bremen', '€60–€100 per person/night', 'Central location, group-friendly facilities, comfortable stay');

-- Insert Bremen restaurants
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Schüttinger Gasthausbrauerei', 'Restaurants', 'German pub fare, local dishes', 'Hinter dem Schütting 12, 28195 Bremen', 'Bremen', '+49 421 337 77 77', 'info@schuettinger.de', 'schuettinger.de', '€9–€15', 'Rustic brewery with hearty meals like Bremer Knipp; large communal tables ideal for groups; offers happy hour deals.'),
('Kismet New Generation', 'Restaurants', 'Turkish fast food (Rollo wraps)', 'Sogestrasse 72, 28201 Bremen', 'Bremen', '+49 421 555 55 55', 'info@kismet-bremen.de', 'kismet-bremen.de', '€3–€6', 'Popular with students; quick service; casual setting; great for a budget-friendly lunch stop.'),
('Plaka Restaurant', 'Restaurants', 'Greek cuisine', 'Berliner Straße 22, 28203 Bremen', 'Bremen', '+49 421 123 4567', 'info@plaka-bremen.de', 'plaka-bremen.de', '€10–€15', 'Family-run with generous portions; welcoming atmosphere; suitable for groups; note: may require reservation due to limited space.'),
('Pannekoekschip Admiral Nelson', 'Restaurants', 'Pancakes (sweet & savory)', 'Schlachte Anleger 3B, 28195 Bremen', 'Bremen', '+49 421 789 1010', 'info@admiralnelson-bremen.de', 'admiralnelson-bremen.de', '€8–€12', 'Unique dining on a ship; fun for kids; offers a variety of pancakes; group-friendly environment.'),
('Coffee Corner', 'Restaurants', 'Café with bagels & salads', 'Ostertorsteinweg 1, 28203 Bremen', 'Bremen', '+49 421 987 6543', 'info@coffeecorner-bremen.de', 'coffeecorner-bremen.de', '€3–€7', 'Cozy spot for light meals; offers soups, salads, and bagels; suitable for small groups; free Wi-Fi available.'),
('Angolino', 'Restaurants', 'Italian trattoria', 'Vor dem Steintor 11, 28203 Bremen', 'Bremen', '+49 421 246 810', 'info@angolino-bremen.de', 'angolino-bremen.de', '€6–€10', 'Cozy atmosphere; serves classic Italian dishes; good for small to medium-sized groups.'),
('Haus am Walde', 'Restaurants', 'German cuisine, beer garden', 'Kuhgrabenweg 2, 28359 Bremen', 'Bremen', '+49 421 123 7890', 'info@hausamwalde-bremen.de', 'hausamwalde-bremen.de', '€10–€15', 'Located near a park; spacious outdoor seating; suitable for larger groups; offers regional dishes.'),
('Bremen Ratskeller', 'Restaurants', 'Traditional German dishes', 'Am Markt 11, 28195 Bremen', 'Bremen', '+49 421 321 676', 'info@ratskeller-bremen.de', 'ratskeller-bremen.de', '€15–€25', 'Offers a historical dining experience in the city''s wine cellar; known for local specialties.');

-- Insert Bruges suppliers
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('Belfry of Bruges (Belfort)', 'Attractions', 'History, architecture, and views', 'Markt 7, 8000 Bruges', 'Bruges', '+32 50 446 111', 'info@visitbruges.be', 'www.visitbruges.be/en/belfry', '€17 per child', 'Iconic tower offering panoramic views; school groups can learn about medieval architecture.'),
('Choco-Story Bruges', 'Attractions', 'Chocolate history and tasting', 'Wijnzakstraat 2, 8000 Bruges', 'Bruges', '+32 50 612 337', 'info@choco-story-brugge.be', 'www.choco-story-brugge.be', '€8.50 per child', 'Interactive exhibits on chocolate making; workshops available for children.'),
('Historium Bruges', 'Attractions', 'Medieval history and interactive exhibits', 'Markt 1, 8000 Bruges', 'Bruges', '+32 50 275 500', 'info@historium.be', 'www.historium.be', '€17 per student', 'Immersive experience recreating medieval Bruges; special rates for school groups.'),
('Canal Boat Tours', 'Attractions', 'Scenic exploration of Bruges'' canals', 'Various docks around Bruges', 'Bruges', '+32 50 330 911', 'info@visitbruges.be', 'www.visitbruges.be/canals', '€9 per child', 'Offers a fun and educational way to view the city; group discounts available.'),
('Frietmuseum', 'Attractions', 'History of Belgian fries', 'Vlamingstraat 33, 8000 Bruges', 'Bruges', '+32 50 345 320', 'info@frietmuseum.be', 'www.frietmuseum.be', '€7.50 per child', 'Fun museum about the history of fries; suitable for younger children and groups.'),
('Begijnhof (Beguinage)', 'Attractions', 'Cultural and religious history', 'Wijngaardstraat, 8000 Bruges', 'Bruges', '+32 50 448 711', 'info@visitbruges.be', 'www.visitbruges.be/en/beguinage', 'Free (museum €1 for children)', 'Peaceful setting for cultural education; great for learning about historical lifestyles.'),
('Gruuthuse Museum', 'Attractions', 'Art, history, and archaeology', 'Dijver 17, 8000 Bruges', 'Bruges', '+32 50 448 722', 'info@museabrugge.be', 'www.museabrugge.be', '€8 per student', 'Offers exhibits on medieval artifacts; child-friendly tours available.'),
('Lace Center (Kantcentrum)', 'Attractions', 'Traditional lace-making demonstration', 'Balstraat 16, 8000 Bruges', 'Bruges', '+32 50 334 261', 'info@kantcentrum.eu', 'www.kantcentrum.eu', '€4 per student', 'Demonstrations and workshops on lace-making, a Bruges specialty; educational for students.'),
('Minnewater Park (Lake of Love)', 'Attractions', 'Nature and scenic beauty', 'Minnewater, 8000 Bruges', 'Bruges', '+32 50 448 711', 'info@visitbruges.be', 'www.visitbruges.be/en/minnewater', 'Free', 'A tranquil park ideal for group walks and relaxation; educational opportunities on ecology.'),
('The Windmills of Bruges', 'Attractions', 'History and engineering', 'Kruisvest, 8000 Bruges', 'Bruges', '+32 50 448 711', 'info@visitbruges.be', 'visitbruges.be', 'Free', 'Scenic walk along the canals; a historic landmark.');

-- Insert Bruges accommodations
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('St. Christopher''s Inn', 'Accommodation', 'Budget-friendly hostel', 'Canal 5, Bruges 8000', 'Bruges', '+32 50 700 400', 'bruges@st-christophers.co.uk', 'www.st-christophers.co.uk', '€20–€35 per person/night', 'Offers dormitory-style rooms; group discounts; close to historical sites and canals.'),
('Hostel Lybeer Bruges', 'Accommodation', 'Traditional Belgian experience', 'Korte Vuldersstraat 31, 8000 Bruges', 'Bruges', '+32 50 341 221', 'info@lybeerhotel.com', 'www.lybeerhotel.com', '€25–€40 per person/night', 'Central location; communal kitchen; activities like walking tours available for groups.'),
('Snuffel Hostel', 'Accommodation', 'Modern and eco-friendly hostel', 'Ezelstraat 42, 8000 Bruges', 'Bruges', '+32 50 338 020', 'info@snuffel.be', 'www.snuffel.be', '€25–€45 per person/night', 'Free breakfast; bike rental; spacious common areas for group activities.'),
('Academie Hotel', 'Accommodation', 'Mid-range hotel near key attractions', 'Wijngaardstraat 7-9, 8000 Bruges', 'Bruges', '+32 50 446 656', 'info@hotelacademie.be', 'www.hotelacademie.be', '€50–€80 per person/night', 'Located near Minnewater Park; offers group deals and family-friendly amenities.'),
('Green Park Hotel Brugge', 'Accommodation', 'Quiet location with outdoor spaces', 'Chartreuseweg 20, 8200 Bruges', 'Bruges', '+32 50 400 300', 'info@greenparkhotelbrugge.com', 'www.greenparkhotelbrugge.com', '€40–€70 per person/night', 'Large garden and outdoor pool; suitable for group relaxation after sightseeing.'),
('Hotel Ibis Brugge Centrum', 'Accommodation', 'Affordable and centrally located hotel', 'Katelijnestraat 65, 8000 Bruges', 'Bruges', '+32 50 330 233', 'info@ibis.com', 'www.ibis.com', '€35–€60 per person/night', 'Walking distance to attractions; offers breakfast buffet and group accommodation options.'),
('Charlie Rockets Hostel', 'Accommodation', 'Budget-friendly with a lively atmosphere', 'Hoogstraat 19, 8000 Bruges', 'Bruges', '+32 50 334 835', 'info@charlierockets.com', 'www.charlierockets.com', '€20–€35 per person/night', 'Features a pub and restaurant; caters to young groups.');

-- Insert Bruges restaurants
INSERT INTO suppliers (name, category, focus, address, city, phone, email, website, approx_price, notes_for_groups) VALUES
('De Halve Maan Brewery Café', 'Restaurants', 'Belgian cuisine', 'Walplein 26, 8000 Bruges', 'Bruges', '+32 50 443 220', 'info@halvemaan.be', 'www.halvemaan.be', '€15–€20', 'Offers a variety of Belgian dishes; great after a brewery tour (non-alcoholic options for kids).'),
('Pasta Presto', 'Restaurants', 'Italian cuisine', 'Langestraat 129, 8000 Bruges', 'Bruges', '+32 50 345 684', 'info@pastapresto.be', 'www.pastapresto.be', '€10–€15', 'Quick and affordable pasta dishes; ideal for group meals with a casual setting.'),
('Frituur De Biezen', 'Restaurants', 'Traditional Belgian fries and snacks', 'Biezenstraat 1, 8000 Bruges', 'Bruges', '+32 50 345 264', 'info@visitbruges.be', 'www.visitbruges.be', '€8–€12', 'Famous for its fries and local snacks; kid-friendly and budget-friendly.'),
('Le Pain Quotidien', 'Restaurants', 'Healthy, casual dining', 'Simon Stevinplein 15, 8000 Bruges', 'Bruges', '+32 50 332 370', 'info@lepainquotidien.com', 'www.lepainquotidien.com', '€12–€18', 'Organic and wholesome meals; suitable for groups with vegetarian options.'),
('Bistro ''t Zwart Huis', 'Restaurants', 'Belgian and European cuisine', 'Kuipersstraat 23, 8000 Bruges', 'Bruges', '+32 50 696 969', 'info@zwarthuis.be', 'www.zwarthuis.be', '€15–€25', 'Unique atmosphere in a historic building; group seating available.'),
('Ellis Gourmet Burger', 'Restaurants', 'Burgers and sides', 'Simon Stevinplein 14, 8000 Bruges', 'Bruges', '+32 50 703 064', 'info@ellisgourmetburger.be', 'www.ellisgourmetburger.be', '€12–€18', 'Known for delicious burgers; group menus and child-friendly options available.'),
('Chez Albert', 'Restaurants', 'Waffles and light meals', 'Breidelstraat 16, 8000 Bruges', 'Bruges', '+32 50 345 678', 'info@chezalbert.be', 'www.chezalbert.be', '€8–€12', 'Specializes in Belgian waffles; perfect for a sweet treat for kids and adults alike.'),
('Sanseveria Bagelsalon', 'Restaurants', 'Bagels and light meals', 'Predikherenstraat 11, 8000 Bruges', 'Bruges', '+32 50 703 573', 'info@sanseveria.be', 'www.sanseveria.be', '€8–€15', 'Offers a variety of creative bagels; casual and relaxed setting for groups.');